In [2]:
import pandas as pd

# Path to your CSV file
file_path = r"C:\Users\Morobang\Documents\GitHub\English Premier League & Championship Analysis\data\England CSV.csv"

# Read the CSV into a DataFrame
df = pd.read_csv(file_path)

# Show the first 5 rows (to verify structure)
print("📄 First 5 Rows:")
display(df.head())

# Filter for HomeTeam = Everton and AwayTeam = Charlton
filtered_df = df[(df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Charlton')]

# Show matching rows
print("\n⚽ Matches where Everton was home and Charlton was away:")
display(filtered_df)

📄 First 5 Rows:

,Date,Season,HomeTeam,AwayTeam,FTH Goals,FTA Goals,FT Result,HTH Goals,HTA Goals,HT Result,...,H Fouls,A Fouls,H Corners,A Corners,H Yellow,A Yellow,H Red,A Red,Display_Order,League
0,16/01/2025,2024/25,Ipswich Town,Brighton & Hove Albion,0,2,A,0.0,1.0,A,...,13.0,14.0,1.0,9.0,2.0,2.0,0.0,0.0,20250116,Premier League
1,16/01/2025,2024/25,Man United,Southampton,3,1,H,0.0,1.0,A,...,7.0,10.0,4.0,4.0,1.0,3.0,0.0,0.0,20250116,Premier League
2,15/01/2025,2024/25,Everton,Aston Villa,0,1,A,0.0,0.0,D,...,17.0,10.0,8.0,5.0,2.0,1.0,0.0,0.0,20250115,Premier League
3,15/01/2025,2024/25,Leicester,Crystal Palace,0,2,A,0.0,0.0,D,...,7.0,6.0,4.0,3.0,0.0,0.0,0.0,0.0,20250115,Premier League
4,15/01/2025,2024/25,Newcastle,Wolves,3,0,H,1.0,0.0,H,...,10.0,13.0,4.0,2.0,0.0,2.0,0.0,0.0,20250115,Premier League

⚽ Matches where Everton was home and Charlton was away:

,Date,Season,HomeTeam,AwayTeam,FTH Goals,FTA Goals,FT Result,HTH Goals,HTA Goals,HT Result,...,H Fouls,A Fouls,H Corners,A Corners,H Yellow,A Yellow,H Red,A Red,Display_Order,League
6716,15/04/2007,2006/07,Everton,Charlton,2,1,H,0.0,0.0,D,...,7.0,15.0,7.0,4.0,0.0,3.0,0.0,0.0,20070415,Premier League
7234,2/01/2006,2005/06,Everton,Charlton,3,1,H,2.0,1.0,H,...,13.0,14.0,5.0,2.0,0.0,2.0,0.0,0.0,20060102,Premier League
7574,22/01/2005,2004/05,Everton,Charlton,0,1,A,0.0,1.0,A,...,13.0,10.0,9.0,5.0,1.0,2.0,0.0,0.0,20050122,Premier League
7979,17/01/2004,2003/04,Everton,Charlton,0,1,A,0.0,1.0,A,...,6.0,14.0,10.0,5.0,4.0,2.0,0.0,0.0,20040117,Premier League
8444,9/11/2002,2002/03,Everton,Charlton,1,0,H,1.0,0.0,H,...,14.0,13.0,7.0,3.0,2.0,3.0,0.0,0.0,20021109,Premier League
8756,29/12/2001,2001/02,Everton,Charlton,0,3,A,0.0,1.0,A,...,16.0,12.0,3.0,6.0,1.0,3.0,0.0,0.0,20011229,Premier League
9312,23/08/2000,2000/01,Everton,Charlton,3,0,H,0.0,0.0,D,...,17.0,15.0,3.0,5.0,2.0,1.0,0.0,1.0,20000823,Premier League
9750,24/04/1999,1998/99,Everton,Charlton,4,1,H,2.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19990424,Premier League

In [3]:
import pandas as pd

# Step 1: Load the CSV
file_path = r"C:\Users\Morobang\Documents\GitHub\English Premier League & Championship Analysis\data\England CSV.csv"
df = pd.read_csv(file_path)

# Step 2: Show all column names
print("📋 All column names in the dataset:")
for col in df.columns:
    print(f"- '{col}'")

# Step 3: Show first 5 rows to inspect structure
print("\n🧾 Sample data:")
display(df.head())  # Use print(df.head()) if not in Jupyter

# OPTIONAL: Step 4 - Try automatic trimming of column names
df.columns = df.columns.str.strip()  # Removes accidental spaces

# Step 5: Filter records (after verifying column names)
# Replace 'HomeTeam' and 'AwayTeam' with actual column names from above output
try:
    filtered_df = df[(df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Charlton')]
    print("\n⚽ Matches where Everton was home and Charlton was away:")
    display(filtered_df)  # Use print(filtered_df) if not in Jupyter
except KeyError as e:
    print(f"\n❌ Column not found: {e}. Check the exact column names printed above.")

📋 All column names in the dataset:
- 'Date'
- 'Season'
- 'HomeTeam'
- 'AwayTeam'
- 'FTH Goals'
- 'FTA Goals'
- 'FT Result'
- 'HTH Goals'
- 'HTA Goals'
- 'HT Result'
- 'Referee'
- 'H Shots'
- 'A Shots'
- 'H SOT'
- 'A SOT'
- 'H Fouls'
- 'A Fouls'
- 'H Corners'
- 'A Corners'
- 'H Yellow'
- 'A Yellow'
- 'H Red'
- 'A Red'
- 'Display_Order'
- 'League'

🧾 Sample data:

,Date,Season,HomeTeam,AwayTeam,FTH Goals,FTA Goals,FT Result,HTH Goals,HTA Goals,HT Result,...,H Fouls,A Fouls,H Corners,A Corners,H Yellow,A Yellow,H Red,A Red,Display_Order,League
0,16/01/2025,2024/25,Ipswich Town,Brighton & Hove Albion,0,2,A,0.0,1.0,A,...,13.0,14.0,1.0,9.0,2.0,2.0,0.0,0.0,20250116,Premier League
1,16/01/2025,2024/25,Man United,Southampton,3,1,H,0.0,1.0,A,...,7.0,10.0,4.0,4.0,1.0,3.0,0.0,0.0,20250116,Premier League
2,15/01/2025,2024/25,Everton,Aston Villa,0,1,A,0.0,0.0,D,...,17.0,10.0,8.0,5.0,2.0,1.0,0.0,0.0,20250115,Premier League
3,15/01/2025,2024/25,Leicester,Crystal Palace,0,2,A,0.0,0.0,D,...,7.0,6.0,4.0,3.0,0.0,0.0,0.0,0.0,20250115,Premier League
4,15/01/2025,2024/25,Newcastle,Wolves,3,0,H,1.0,0.0,H,...,10.0,13.0,4.0,2.0,0.0,2.0,0.0,0.0,20250115,Premier League

⚽ Matches where Everton was home and Charlton was away:

,Date,Season,HomeTeam,AwayTeam,FTH Goals,FTA Goals,FT Result,HTH Goals,HTA Goals,HT Result,...,H Fouls,A Fouls,H Corners,A Corners,H Yellow,A Yellow,H Red,A Red,Display_Order,League
6716,15/04/2007,2006/07,Everton,Charlton,2,1,H,0.0,0.0,D,...,7.0,15.0,7.0,4.0,0.0,3.0,0.0,0.0,20070415,Premier League
7234,2/01/2006,2005/06,Everton,Charlton,3,1,H,2.0,1.0,H,...,13.0,14.0,5.0,2.0,0.0,2.0,0.0,0.0,20060102,Premier League
7574,22/01/2005,2004/05,Everton,Charlton,0,1,A,0.0,1.0,A,...,13.0,10.0,9.0,5.0,1.0,2.0,0.0,0.0,20050122,Premier League
7979,17/01/2004,2003/04,Everton,Charlton,0,1,A,0.0,1.0,A,...,6.0,14.0,10.0,5.0,4.0,2.0,0.0,0.0,20040117,Premier League
8444,9/11/2002,2002/03,Everton,Charlton,1,0,H,1.0,0.0,H,...,14.0,13.0,7.0,3.0,2.0,3.0,0.0,0.0,20021109,Premier League
8756,29/12/2001,2001/02,Everton,Charlton,0,3,A,0.0,1.0,A,...,16.0,12.0,3.0,6.0,1.0,3.0,0.0,0.0,20011229,Premier League
9312,23/08/2000,2000/01,Everton,Charlton,3,0,H,0.0,0.0,D,...,17.0,15.0,3.0,5.0,2.0,1.0,0.0,1.0,20000823,Premier League
9750,24/04/1999,1998/99,Everton,Charlton,4,1,H,2.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19990424,Premier League